### PR TITLE
Suppress should scroll for single app manager

### PR DESCRIPTION
**Pull request by unkcpz**

### CODE REVIEW

**Comment by unkcpz** [comment]
I don't know why this is only happening now. I think previously it is all fine.

**Comment by unkcpz** [comment]
I cannot reproduce it on my laptop, will try tomorrow on my workstation.

**Comment by danielhollas** [comment]
I just experienced this when I added some debugging output after the app. 

obrazek

**Review by danielhollas — APPROVED** [review]

**Comment by unkcpz** [comment]
I think we didn't have this issue because the single app widget is always not very big. With some output in the cell, the issue will happen. The change is needed.

@danielhollas thanks for checking and approving.

**Pull request merged**
