### PR TITLE
Fix version mismatch

### PR DESCRIPTION
**Pull request by danielhollas**
In the last release, the version was not actually updated. 

This didn't broke anything, because this package is not published anywhere, and is installed in aiidalab-docker-stack directly from the git repo based on the git version tag, which was correct. But if you try to identify the version in the current image
```
mamba list aiidalab-home
```
it will print the old version.

### CODE REVIEW

**Comment by danielhollas** [comment]
@unkcpz would you mind giving me access to this repo as well? :blush:

**Comment by unkcpz** [comment]
> @unkcpz would you mind giving me access to this repo as well? 😊

Sure, done! You gradually have your hands on all repos 😄

**Review by unkcpz — APPROVED** [review]
Looks good to me. But why it is not updated? The variable is in the bumpver setup of `setup.cfg`.

**Comment by danielhollas** [comment]
The last release was done by hand, the bumpver was introduced only in the last commit if you look at the git history.

**Comment by unkcpz** [comment]
I see, thanks for check!

**Comment by danielhollas** [comment]
Btw: I caught this by writing a new test as part of https://github.com/aiidalab/aiidalab-docker-stack/pull/327 :-)

**Pull request merged**
