### PR TITLE
Bump version v22.08.0 -> v22.11.0.

### PR DESCRIPTION
**Pull request by danielhollas**
This release doesn't really bring anything new, but I think it is better to have it to resolve the version inconsistency and prevent confusion (see last commit on the master branch).

Also, I used bumpver for the first time, it's quite nice! :factory_worker:

### CODE REVIEW

**Comment by yakutovicha** [comment]
@danielhollas, why did you create a PR for the release? In principle, bumpver should've pushed to the master branch and should've made the release tag all by itself.

**Comment by danielhollas** [comment]
@yakutovicha yep, but I do not have rights to push to master branch I don't think. :-)

**Comment by unkcpz** [comment]
> @yakutovicha yep, but I do not have rights to push to master branch I don't think. :-)

I think you have, no? But don't worry, just let us know and we'll release a new version if needed.

**Comment by danielhollas** [comment]
Thanks @unkcpz. I'll work with @yakutovicha for giving me the release permissions here. Closing this.

**Pull request closed without merging**
