### PR TITLE
Remove not depracated git_setup.ipynb

### PR DESCRIPTION
**Pull request by unkcpz**
@yakutovicha This notebook is not used anymore, correct?

### CODE REVIEW

**Comment by danielhollas** [comment]
Hmm, this actually looks kinda useful. Perhaps this could be a part of the new "Settings" tab that we've discussed as part of making AWB into a library.

**Comment by unkcpz** [comment]
Why do you think it is useful? I think it basically provides for AiiDAlab user git access but in my opinion, the "production" AiiDAlab user doesn't need this and we (developers) need git setup but since we introduce the aiidalab-launch to start the local development environment this again not been used.

**Comment by danielhollas** [comment]
Yeah, I guess for production this shouldn't be there.

**Review by danielhollas — APPROVED** [review]
LGTM but please wait what @yakutovicha has to say before we delete this.

**Review by yakutovicha — APPROVED** [review]
oh, yeah. That is something extreeeeemely old and not used anymore.

**Pull request merged**
