### PR TITLE
Merge branch 'develop' to 'master'

### PR DESCRIPTION
**Pull request by yakutovicha**

### CODE REVIEW

**Comment by yakutovicha** [comment]
@ltalirz if you merge it yourself, please merge using the merge commit.

**Comment by ltalirz** [comment]
I guess this is stuff you discussed with Simon - I suggest you either let him review your just merge yourself

**Comment by yakutovicha** [comment]
this commit is just technical stuff: merge develop into master. The PRs #30 and #31 were agreed with @csadorf.

**Comment by yakutovicha** [comment]
> fine, although with the caveat that this approval doesn't mean much ;-)

I could have merged it without the approuval, just trying to follow the work pattern.

**Pull request merged**
